[character]
success_symbol = "[â¯](blue)[â¯](cyan)[â¯](white)"
error_symbol = "[â¯](red)[â¯](red)[â¯](red)"

[directory]
format = "[$path](blue)[$read_only](red) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "242"

[git_status]
format = "[$conflicted$stashed$ahead_behind](242) "
stashed = "â‰¡"
conflicted = "âœ˜"

[conda]
format = "[$symbol $environment](dimmed green) "
symbol = "ğŸ"

[java]
disabled = true

[python]
disabled = true
